import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data: session } = useSession();
  const { data: posts, isLoading } = api.posts.getAll.useQuery();
  console.log(posts);
  if (isLoading) return <div>Loading...</div>;
  if (!posts) return <div>Something went wrong</div>;
  const CreatePostWizard = () => {
    // const { data: session } = useSession();
    const user = session?.user;

    if (!user) return null;
    console.log(user)
    return (
      <div className="flex w-full gap-3">
        <img
          src={user?.image}
          className="h-14 w-14 rounded-full"
          alt="Profile image"
        />
        <input
          placeholder="Type some emojies!"
          className="grow bg-transparent outline-none"
        />
      </div>
    );
  };
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="h-screen w-full border-x border-slate-400 md:max-w-2xl">
          <div className="border-b border-slate-400 p-4">
            {session ? (
              <div>
                <CreatePostWizard />
              </div>
            ) : (
              <button onClick={() => void signIn()}>Sign In</button>
            )}
          </div>
          <div className="flex flex-col">
            {posts?.map((post) => {
              return (
                <div key={post.id} className="border-b border-slate-400 p-8">
                  {post.content}{" "}
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
